rancher/aks-operator

README.md
controller/aks-cluster-config-handler.go
crds/aksclusterconfig.yaml
examples/create-example.yaml
examples/import-example.yaml
internal/aks/client.go
internal/aks/create.go
internal/aks/delete.go
internal/aks/exists.go
internal/utils/map.go
internal/utils/parse.go
pkg/apis/aks.cattle.io/v1/types.go

* Split AKS specific functions into new package module
* Refactor aks-operator controller
- Add more options to be updated by updateUpstreamClusterState
- Move validation function for orchestration version to UI proxy
- Stop removing Resource Group after cluster removal

Refactor and split AKS functions

---

controller/aks-cluster-config-handler.go

`err` is nil at both of these points, so it's unnecessary to log it. Use
the cluster status instead.

Fix error messages

---

internal/aks/create.go

Without this change, the subnet ID renders the VirtualNetwork and Subnet
pointer values as hexadecimal values instead of the strings they
represent, and the virtual network cannot be found.

Fix VNet subnet ID builder

---

charts/aks-operator/questions.yaml
scripts/package-helm

The chart version sed command was inadvertently overwriting the
rancher-version annotation. This change fixes that issue.
Issue:
https://github.com/rancher/rancher/issues/32293

Fix version sed for chart version

---

pkg/apis/aks.cattle.io/v1/types.go

Opt into a new field type in norman that will convert `*string`s to
`{nullable: true, type: nullablestring}` in the API schema, and back to
`*string` in the generated client code. Without this, `*string`s get
translated to just `string` in the generated code, which breaks clients'
ability to set fields to nil.
https://github.com/rancher/rancher/issues/32440

Set norman type to 'nullablestring' for *strings

---

charts/aks-operator-crd/templates/crds.yaml
controller/aks-cluster-config-handler.go
internal/aks/client.go
internal/aks/create.go
pkg/apis/aks.cattle.io/v1/types.go
pkg/apis/aks.cattle.io/v1/zz_generated_deepcopy.go

Add new option to addon profile HTTPApplicationRouting which
configures an Ingress controller in AKS cluster.
Issue: https://github.com/rancher/rancher/issues/32674

Add HTTP Application Routing

---

internal/aks/create.go

Fix enabling autoscaling for nodepools after AKS cluster was provisioned
Issue: https://github.com/rancher/rancher/issues/32956

Fix autoscaling for nodedools

---

pkg/aks/create.go

It was missing AvailabilityZones option in CreateOrUpdateAgentPool
Issue: https://github.com/rancher/rancher/issues/32960

Add availability zones in node pools

---

pkg/apis/aks.cattle.io/v1/types.go

norman removed the 'nullablestring' type in favor of a 'pointer'
attribute for field types[1]. In addition to string pointers, this can
be used on maps and slices to indicate the generated client code should
become a pointer, even if the original type was not.
[1] https://github.com/rancher/norman/pull/400
https://github.com/rancher/rancher/issues/32440
https://github.com/rancher/rancher/issues/32553

Change to 'pointer' for norman fields

---

.drone.yml
Dockerfile.dapper
package/Dockerfile
scripts/package

In addition to using the SLES image for the aks-operator image, the
dapper image is also switched to using SLES.
A side effect of this is that docker will no longer be installed in the
dapper image. Instead, a new pipeline step is added to build the image
on pull requests.

Use same SLES image as Rancher

---

charts/aks-operator/templates/deployment.yaml
package/Dockerfile
package/entrypoint.sh

The SLE image requires that c_rehash is run before additional trusted CAs
will be detected. Therefore, an entrypoint script is added to accomplish
this.
In addition, fsGroup is added so that c_rehash (which is run as the
aks-operator user) can read the cert that is mounted.
Issue:
https://github.com/rancher/rancher/issues/31846

Run c_rehash before launching the operator

---

controller/aks-cluster-config-handler.go
pkg/aks/create.go

Without this change, setting ServicePrincipalProfile on a cluster update
causes an error: "Changing property 'servicePrincipalProfile.clientId'
is not allowed", even though the clientID is not different. This change
checks whether the cluster is in an updating state before trying to set
the ServicePrincipalProfile on the cluster object.
Additionally, since DNSPrefix is nil for imported clusters, this value
was being changed to the cluster name, which might not be the true
value, and so was causing the operator to try to change it even though
it is immutable. This change makes it a required property, which is
already the case in UI, and ignores it if it is nil which will be the
case for imported clusters.
https://github.com/rancher/rancher/issues/33536

Don't attempt to update immutable properties

---

controller/aks-cluster-config-handler.go
pkg/aks/create.go

https://github.com/rancher/rancher/issues/34244
If you enable container monitoring, httpApplicationRouting would never turn on.
The addonProfiles were being overwritten instead of appended too.  This caused the operator to continue updating the cluster infinitely.  I fixed this logic so that an combination of monitoring and http application routing can be configured.  I also fixed the operator attempting to update the cluster when it was already in an updating state.

fixed addon profiles overwriting each other

---

charts/aks-operator/templates/_helpers.tpl
charts/aks-operator/values.yaml

Rancher sets the default registry under
`global.cattle.systemDefaultRegistry`. Without this change, the chart
wasn't picking up the setting and would still try to pull images from
dockerhub. This change aligns the setting with the way Rancher expects
to use it and with the way other charts expose it.
https://github.com/rancher/rancher/issues/35485

Fix system default registry setting

---

charts/aks-operator/Chart.yaml

The annotations were also rearranged to be in alphabetical order.
Issue:
https://github.com/rancher/rancher/issues/35100

Add kube-version annotation to chart

---

pkg/apis/aks.cattle.io/v1/types.go

Address https://github.com/rancher/rancher/issues/36128.
A KEv2 cluster imported with the rancher2 terraform provider will currently delete all node groups on import if no node groups are specified in the terraform config.
This is happening because the NodeGroups cluster config field (and all slices and maps) in the KEv2 operators have the norman:pointer tag. The problem is that the norman:pointer tag is added to fields that are already pointers. When node groups is not specified in the terraform config, terraform sets the node group field in the management cluster yaml as an empty array instead of null. If node groups is an empty array, Rancher deletes all node groups from the imported cluster because that is the template given: no node groups. Removing the incorrect tag will make node …

Remove incorrect norman:pointer tags from AKS operator

---

controller/aks-cluster-config-handler.go

Issue: https://github.com/rancher/rancher/issues/36425 
The customer had an Azure setup where they had log analytics enabled on an AKS cluster, but either didn't have the OMS agent configured or it was misconfigured. This caused a panic in Rancher. I reproduced the issue internally, and fixed it by adding checks for a nil or empty OMS agent profile configuration.
1. Added test code to a local copy of `rancher/aks-operator` simulating a nil or misconfigured OMS agent profile in an Azure portal setup
2. Ran standalone `ask-operator`
3. Ran an instance of Rancher v2.6-head and scaled the ask-operator deployment count to 0
4. Created an AKS cluster through Rancher
5. Checked that an invalid oms agent configuration error is seen in the UI

Add checks for misconfigured oms agent

---

pkg/aks/create.go

Issue: https://github.com/rancher/rancher/issues/36959
Problem
Users were unable to provision AKS clusters using a basic load balancer. When creating an AKS cluster with a basic load balancer, Rancher was setting the node pool AvailabilityZones field to an empty list (as availability zones cannot be used with a basic load balancer). However, this caused Azure to mistakenly believe that we had provided some availability zones, preventing the use of a basic load balancer.
Solution
This problem has been resolved by ensuring that any empty AvailabilityZones slices are set to nil.
Testing
I've created several AKS clusters using a basic load balancer and they have provisioned correctly and transitioned into an active state without error. Cluster state syncing also persists the `nil` …

[2.6.5] Fix basic AKS load balancer

---

controller/aks-cluster-config-handler.go
pkg/aks/exists.go

Issue: https://github.com/rancher/rancher/issues/37955
When you try to provision an AKS cluster with the same name and resource group as one that already exists in Azure, an error appears in the rancher UI because the [CreateOrUpdate call to AKS](https://github.com/rancher/aks-operator/blob/a32c2bf0c3254301d1257345d4db786fef49162e/pkg/aks/create.go#L186) fails.
Added check for existing cluster in the aks operator `CreateCluster` function. If the cluster name in the specified resource group already exists in Azure, an error `cluster [name] already exists in Azure. Please import it` will now display in the rancher UI. This is much clearer for the customer and short circuits unnecessary API calls being made to create the managed cluster.
Smoke test
* Create an AKS cluster in Azure Portal …

Add duplicate cluster check

---

charts/aks-operator/templates/deployment.yaml
charts/aks-operator/values.yaml

Related to https://github.com/rancher/rancher/issues/37927
The purpose of this PR is to add the ability to set a priorityClassName for pods installed by Rancher.

Adds priorityClassName to deployments.

---

controller/aks-cluster-config-handler.go

Issue: https://github.com/rancher/rancher/issues/39259
When a customer creates an AKS cluster in Azure portal with monitoring configured (OMS agent profile), then import it into Rancher, Rancher will panic [here](https://github.com/rancher/aks-operator/blob/dc721007245a04f953523e91e01174b79f104e1e/controller/aks-cluster-config-handler.go#L700) because in this upstream config
```
"addonProfiles": {
"omsagent": {
"config": {
"logAnalyticsWorkspaceResourceID": "/subscriptions/<workspace subscription id>/resourcegroups/<workspace group>/providers/microsoft.operationalinsights/workspaces/<workspace name>"
},
"enabled": true
}
}
```
The `logAnalyticsWorkspaceResourceID` contains `resourceGroups` instead of `resourcegroups` like Rancher expects …

Add checks for monitoring workspace group/name

---

pkg/aks/create.go

For changing AddonProfiles for imported AKS cluster, we have to check first if AddonProfiles for aksCluster spec is not nil. If yes then it has to be initialized.
Fixes: https://github.com/rancher/rancher/issues/40087
Signed-off-by: Michal Jura <mjura@suse.com>

Check nil value for aksCluster AddonProfiles

---

charts/aks-operator-crd/templates/crds.yaml
controller/aks-cluster-config-handler.go
pkg/aks/create.go
pkg/apis/aks.cattle.io/v1/types.go
pkg/apis/aks.cattle.io/v1/zz_generated_deepcopy.go

Currently, node pool's subnet id is not set when the operator updates a node pool. This makes azure client try to delete it if the value is set to nil. The PR should fix by passing this value if possible.
Fixes: https://github.com/rancher/rancher/issues/40087

Pass node pool's subnet id to azure client

---

.github/workflows/build.yaml
.github/workflows/verify.yaml
Makefile

Add a `build` workflow and `verify` to ensure that we didn't forget to run `make generate` if something changed.

Add new github workflows

---

charts/aks-operator-crd/templates/crds.yaml
controller/aks-cluster-config-handler.go
pkg/aks/create.go
pkg/apis/aks.cattle.io/v1/types.go
pkg/apis/aks.cattle.io/v1/zz_generated_deepcopy.go

Backport of:
- https://github.com/rancher/aks-operator/pull/76
- https://github.com/rancher/aks-operator/pull/77
Fixes for https://github.com/rancher/rancher/issues/40087 needed by Rancher v2.6

[2.6] Pass node pool's subnet id to azure client

---

pkg/aks/check.go
pkg/aks/check_test.go
pkg/aks/create.go
pkg/aks/create_test.go
pkg/aks/delete_test.go
pkg/aks/update.go
pkg/aks/update_test.go

This PR adds more unit tests for azure services. There are no logical changes in cluster create/update actions.

Add more unit tests for azure services

---

controller/aks-cluster-config-handler.go
pkg/aks/check.go
pkg/aks/check_test.go
pkg/aks/client.go
pkg/aks/create.go

Module aks-operator is imported by Rancher and functions:
- BuildUpstreamClusterState
https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/management/clusterupstreamrefresher/aks_upstream_spec.go#L14
- GetCachedTenantID
https://github.com/rancher/rancher/blob/release/v2.7/pkg/api/norman/customization/aks/handler.go#L247
- GetClusterKubeConfig
https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/management/aks/aks_cluster_handler.go#L442
- CheckLogAnalyticsWorkspaceForMonitoring
https://github.com/rancher/rancher/blob/release/v2.7/pkg/kontainer-engine/drivers/aks/aks_driver.go#L718
have to be public, because they are used by Rancher.
Signed-off-by: Michal Jura <mjura@suse.com>

Fix Rancher integration

---

controller/aks-cluster-config-handler.go
pkg/aks/client.go

For future implementation:
- change `BuildUpstreamClusterState` function definition and pass cluster client object instead of passing secrets and creating cluster client inside of it
- adjust Rancher integration  in https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/management/clusterupstreamrefresher/aks_upstream_spec.go#L14 and use new function definition

Make Azure services compliant with Rancher

---

test/e2e/basic_cluster_test.go
test/e2e/suite_test.go

This PR introduces an e2e test that adds and then removes a node pool from the aks cluster.

Add an e2e test for node pools

---

pkg/aks/update.go

Check if desiredCluster.DNSPrefix is not nil before using it as pointer
Fixes: https://github.com/rancher/aks-operator/issues/93

Check nil for desiredCluster.DNSPrefix

---

.github/dependabot.yml
.github/workflows/update-rancher-dep.yaml
.updatecli/updatecli.d/bump-rancher-dep.yaml

Introduce a GitHub action that uses https://www.updatecli.io/ to automatically bump aks version in rancher when needed. The action should be run manually from GitHub actions tab.

Automate operator version bump in rancher

---

Makefile
controller/aks-cluster-config-handler.go
controller/aks-cluster-config-handler_test.go
controller/external.go
controller/suite_test.go
go.mod
go.sum
pkg/test/cleanup.go
pkg/test/envtest.go

This PR introduces the usage of [envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) for writing unit tests. Envtest will help us test the controller with a real client.

Use envtest for testing controller package

---

pkg/aks/create.go
pkg/aks/create_test.go

Fixes https://github.com/rancher/aks-operator/issues/153

Add support to use Existing VNET and subnet for kubenet plugin

---

README.md
controller/aks-cluster-config-handler.go
pkg/aks/client.go

Fixes: https://github.com/rancher/aks-operator/issues/98
(cherry picked from commit 41a68e8345dc49338cf7cc42a93ad09d9afd7318)

Add multi-environment support for AKS

---

controller/aks-cluster-config-handler.go
controller/aks-cluster-config-handler_test.go
controller/external.go

Possibly fixes: https://github.com/rancher/aks-operator/issues/98
Signed-off by: Furkat Gofurov (furkat.gofurov@suse.com)

🐛  Fix aks credentials passing to buildUpstreamClusterState() func

---

Makefile
scripts/setup-kind-cluster.sh
test/e2e/config/config.yaml
test/e2e/suite_test.go
test/e2e/templates/basic-cluster.yaml

Update k8s version because 1.24.6 was deprecated by Microsoft.

Update k8s version in e2e tests

---

controller/aks-cluster-config-handler.go
controller/aks-cluster-config-handler_test.go

For imported private clusters with private DNS zones we can skip setting dnsPrefix, because it will be nil value. DNSPrefix can be updated for existing clusters.
Issue: https://github.com/rancher/aks-operator/issues/169

Skip updating dnsPrefix for private DNS zones

---

Makefile
scripts/setup-kind-cluster.sh

If the chart version is set to some unrealistically high version like 900, rancher will not reconcile it. Currently, when aks controller starts returning errors rancher will try to fix the chart:
```
mac:aks-operator ademicev$ kubectl get deployment aks-config-operator -n cattle-system -o yaml | grep image:
image: ghcr.io/rancher/aks-operator:v0.0.0-fbfbe49
mac:aks-operator ademicev$ kubectl get deployment aks-config-operator -n cattle-system -o yaml | grep image:
image: rancher/aks-operator:v1.1.0
```
changes in the PR will prevent this from happening

Prevent rancher from downgrading chart version

---

examples/create-example.yaml

Add `dnsPrefix` option to create example AKS cluster, otherwise it will fail.

Add dnsPrefix to create example cluster

---

charts/aks-operator-crd/templates/crds.yaml
controller/aks-cluster-config-handler.go
examples/create-example-udr.yaml
examples/create-example.yaml
pkg/aks/create.go
pkg/aks/create_test.go
pkg/apis/aks.cattle.io/v1/types.go
pkg/apis/aks.cattle.io/v1/zz_generated_deepcopy.go

Issue https://github.com/rancher/rancher/issues/38560

Enable AKS to use Outbound type of userDefinedRouting

---

.golangci.yml
controller/aks-cluster-config-handler.go
pkg/aks/check.go
pkg/aks/client.go
pkg/aks/create.go
pkg/aks/update.go
pkg/codegen/main.go
pkg/test/cleanup.go
pkg/test/envtest.go
test/e2e/config/config.go

This PR:
- Enables more linters in the .golangci.yaml to have a better aligned package import aliases
- Fixes all lint errors as a consequence of newly added linters

🌱 Enable more linters in aks operator

---

.github/workflows/nightly-publish.yaml

This change adds a enw GHA workflow that will build an image every night and publish it to ttl.sh.

chore: added nightly image publish

---

.github/workflows/nightly-publish.yaml

This updates the nighlt GHA workflow so that it publishes the charts to ttl.sh so that they can be used for testing.

feat: publish nightly charts

---

pkg/aks/create.go
pkg/aks/create_test.go

This is helpful when the Service Principal and the Resource group do not belong in the same Tenant.
Before this change trying to do so would give error showing that the ClientID was not found under TenantID of the Resource group.

Assign TenantID to managed cluster identity

---

.github/scripts/update-rancher-charts.sh

When creating a PR against rancher/charts while releasing a new version of the operator, if `REPLACE=true` (e.g. bumping rc versions) and `release.yaml` in the charts repository is empty (this file is periodically cleaned), the workflow will not update the release file with the updated versions.
This change adds an extra validation when `REPLACE=true`, and only tries to substitute versions if `release.yaml` already contains an entry for `rancher-aks-operator`. If it is not, it will populate the file treating it as empty.
This is equivalent to the change applied to `eks-operator` in https://github.com/rancher/eks-operator/pull/200.

Adapt update-rancher-charts to support an empty release.yaml file

---

test/e2e/templates/basic-cluster.yaml

Bump K8S version in e2e tests, 1.25.5 is no longer supported by AKS

Bump K8S version in e2e tests

---

.github/workflows/update-rancher-dep.yaml

Using the GH workflow with go version 1.20 seems to be having [problems](https://github.com/rancher/aks-operator/actions/runs/6172160893/job/16753012448) with package downloads where using go version 1.21 solves it, so bumping the go version in rancher/rancher repo PR opening GH action

Bump go version to 1.21.0 in update rancher dep GH workflow

---

controller/aks-cluster-config-handler.go

Issue: https://github.com/rancher/aks-operator/issues/294 (cherry picked from commit 1bbce8e781ae8adf387d3c22e5c33d457f4a95a4)

[2.8] Fix for updating imported clusters

---

.github/dependabot.yml

We have to check outdated dependency also for `release-v2.8` and `release-v2.7` branches
Issue #

Improve dependabot conf to track other branches

---

.github/dependabot.yml

Adds `azure-sdk-for-go` dependency to dependabot ignore list in all branches. We are intending to track bumping of that dependency in https://github.com/rancher/aks-operator/issues/287. Once #287 is completed, it can be removed from ignore list

🌱 Add azure-sdk-for-go dependency to dependabot ignore list in all branches

---

.github/workflows/apidiff.yaml

For the last couple of days we've had [API diff validation workflow failing on new PRs](https://github.com/rancher/aks-operator/actions/runs/7534808581/job/20509794469?pr=355).
After some investigation, it looks like this matches `joelanford/go-apidiff`'s new [release](https://github.com/joelanford/go-apidiff/releases). As we're using the latest version [here](https://github.com/rancher/aks-operator/blob/ba933df3b5b5fc12bb8a13963ae301f878af0c59/.github/workflows/apidiff.yaml#L14), CI is failing because our workflow is configured to use Go 1.18 while this new API diff action requires >=1.19.
This PR updates the workflow's Go version to match the project's (Go 1.20).
Issue #359  …

chore: bump apidiff.yaml go version

---

.github/dependabot.yml

Dependabot should ignore `rancher/wrangler` version bumps as it is updated manually. This change also aligns `dependabot.yml`'s format with other providers (refer to `gke-operator` [here](https://github.com/rancher/gke-operator/blob/main/.github/dependabot.yaml)).
Issue #357 
**Checklist**:

chore: add dependabot ignore for rancher/wrangler

---

.github/workflows/apidiff.yaml

Backport `apidiff.yaml` Go version update to `release-v2.7` to avoid PR CI failures (e.g. https://github.com/rancher/aks-operator/pull/351).
Issue #
**Checklist**:

chore: bump apidiff.yaml go version - backport to v2.7

---

.github/dependabot.yml

Add rule for dependabot to ignore wrangler updates and a new block for `release-v2.9`.
Issue #
**Checklist**:

Dependabot ignore wrangler version main

---

Dockerfile.dapper
package/Dockerfile

Issue: https://github.com/rancher/aks-operator/issues/427
Issue #
**Checklist**:

security: bump operator base image to bci-micro:15.5

---

Dockerfile.dapper
package/Dockerfile

Issue: https://github.com/rancher/aks-operator/issues/427 (cherry picked from commit 31fe83bfc7725e8ce8407853d5958135a6a8d883)
Issue #
**Checklist**:

[v2.7] security: bump operator base image to bci-micro:15.5 

---

controller/aks-cluster-config-handler.go
controller/aks-cluster-config-handler_test.go
go.mod
go.sum
pkg/aks/convert.go
pkg/aks/create.go
pkg/aks/create_test.go
pkg/aks/delete_test.go
pkg/aks/get.go
pkg/aks/services/agentpools.go
pkg/aks/services/managedclusters.go
pkg/aks/services/mock_services/agentpools_mock.go
pkg/aks/services/mock_services/managedclusters_mock.go
pkg/aks/update.go
pkg/aks/update_test.go

The previous version of the code used `retry.OnError` in order to retry a synchronous API call that updated a cluster's tags. This is no longer necessary when using the new Azure SDK as the `poller.PollUntilDone` method has the same semantics.  
Issue #132 
**Checklist**:

[v2.9] Fix panic when updating tags

---

controller/aks-cluster-config-handler.go
controller/aks-cluster-config-handler_test.go
go.mod
go.sum
pkg/aks/convert.go
pkg/aks/create.go
pkg/aks/create_test.go
pkg/aks/delete_test.go
pkg/aks/get.go
pkg/aks/services/agentpools.go
pkg/aks/services/managedclusters.go
pkg/aks/services/mock_services/agentpools_mock.go
pkg/aks/services/mock_services/managedclusters_mock.go
pkg/aks/update.go
pkg/aks/update_test.go

The previous version of the code used retry.OnError in order to retry a synchronous API call that updated a cluster's tags. This is no longer necessary when using the new Azure SDK as the poller.PollUntilDone method has the same semantics.
Issue #132
**Checklist**:

Fix panic when updating tags

---

.github/workflows/apidiff.yaml
.github/workflows/e2e-branch.yaml
Makefile

Replace unapproved GH Actions with approved ones. To [enhance security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), the 3rd-party GH Action used to install `kind` is pinned to a commit SHA. Note that dependabot will [update](https://github.com/dependabot/dependabot-core/issues/4691) both the commit SHA and the human-readable value next to it.
Issue https://github.com/rancher/highlander/issues/89
**Checklist**:

fix: Replace  unapproved GH Actions with approved ones

---

test/e2e/templates/basic-cluster.yaml

Bump version of k8s used for e2e test. 1.26.10 is no longer supported in AKS in the eastus region.
**Checklist**:

fix: Bump version of k8s used for e2e test

---

Dockerfile.dapper

Bumped Go version to fix CVE-2024-24790
Issue: https://github.com/rancher/aks-operator/issues/564
**Checklist**:

fix: Bump Go version to fix CVE-2024-24790

---

test/e2e/config/config.yaml

Use v2.9-head version of Rancher for e2e tests.
**Checklist**:

[v2.9] fix: Use v2.9-head version of Rancher for e2e tests

---

test/e2e/config/config.yaml
test/e2e/suite_test.go

This PR updates the e2e tests for `release-v2.9` to use the latest development Rancher Helm chart (currently `2.9.0-rc1`) and overrides the image tag with `v2.9-head`
**Checklist**:

[v2.9] fix: Use version v2.9-head of Rancher for e2e tests

---

test/e2e/config/config.yaml
test/e2e/suite_test.go

This PR updates the e2e tests for `release-v2.8` to use the latest Rancher Helm chart (currently `2.8.5`) and overrides the image tag with `v2.8-head`
**Checklist**:

[v2.8] fix: Use version v2.8-head of Rancher for e2e tests 

---

.drone.yml
.github/workflows/release.yaml
.goreleaser.yaml

Up until recently, creating a new GitHub release (and associated artifacts) when a new tag was created, was being done using Drone CI. Now that Drone CI has been deprecated, there is a GitHub Actions workflow that is responsible for doing this. In fact, most of the work is delegated to goreleaser which is being invoked as part of that workflow.
Issue #573
**Checklist**:

ci: Add goreleaser config and update release workflow

---

.drone.yml
.github/workflows/release.yaml
.goreleaser.yaml
.trivyignore

Up until recently, creating a new GitHub release (and associated artifacts) when a new tag was created, was being done using Drone CI. Now that Drone CI has been deprecated, there is a GitHub Actions workflow that is responsible for doing this. In fact, most of the work is delegated to goreleaser which is being invoked as part of that workflow.
Cherry pick of the commits of https://github.com/rancher/aks-operator/pull/575
Issue #573 
**Checklist**:

[v2.7] ci: Add goreleaser config and update release workflow 

---

.github/workflows/release.yaml

Specify the exact tag for the new release. This is necessary because by default, goreleaser sorts tags by name before selecting which tag to release, which causes problems when >1 tags point to the same commit (un-rc process).  From https://goreleaser.com/cookbooks/set-a-custom-git-tag/
Issue #596 
**Checklist**:

ci: Specify the exact tag for the new release

---

.github/workflows/release.yaml

Specify the exact tag for the new release. This is necessary because by default, goreleaser sorts tags by name before selecting which tag to release, which causes problems when >1 tags point to the same commit (un-rc process). From https://goreleaser.com/cookbooks/set-a-custom-git-tag/
Issue #596 
**Checklist**:

[v2.9] ci: Specify the exact tag for the new release

---

.github/workflows/release.yaml

Specify the exact tag for the new release. This is necessary because by default, goreleaser sorts tags by name before selecting which tag to release, which causes problems when >1 tags point to the same commit (un-rc process). From https://goreleaser.com/cookbooks/set-a-custom-git-tag/
Issue #596 
**Checklist**:

[v2.8] ci: Specify the exact tag for the new release

---

charts/aks-operator/templates/deployment.yaml

1. Restrict container from acquiring additional privileges (`securityContext.allowPrivilegeEscalation`)
2. Mount container's root filesystem as read only (`securityContext.readOnlyRootFilesystem`)
3. Ensure that container won't be started as privileged container (`securityContext.privileged`)
Issue: https://github.com/rancher/aks-operator/issues/591
Issue #
**Checklist**:

Improve securityContext for operator Deployment

---

controller/aks-cluster-config-handler.go
pkg/aks/update.go
pkg/aks/update_test.go

(cherry picked from commit 08974fc3330e57b06dba4fe574f1c9e3b1782341)
Issue #
**Checklist**:

Fix logic for Authorized IP ranges

---

controller/aks-cluster-config-handler.go
pkg/aks/update.go
pkg/aks/update_test.go

Fix logic for updating Authorized IP ranges:
- all settings should be overwrite for AKS clusters provisioned by Rancher
- for imported clusters options should be merged with downstream cluster
Issue: https://github.com/rancher/aks-operator/issues/592
Issue #
**Checklist**:

[v2.9] Fix logic for Authorized IP ranges

---

controller/aks-cluster-config-handler.go
controller/aks-cluster-config-handler_test.go
pkg/aks/create.go
pkg/aks/create_test.go

The monitoring addon was not being disabled as per the spec.
Issue #584 
**Checklist**:

fix: Disable monitoring addon when spec.Monitoring is false

---

controller/aks-cluster-config-handler.go

Occasionally when a conflict occurs during the reconciliation process, the `config` object that is returned is non-nil but empty, causing logs to be missing fields. 
Issue #665 
To address the conflict, the [RetryOnConflict function](https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict) was used to query the resource and attempt the operation again, if the error returned is a conflict error.
**Checklist**:

fix: Retry operation on conflict

---

main.go

Logrus has multiple debug outputs across the codebase but we don't seem to be setting the flag to enable the needed log level

Add debug flag for log level

---

controller/aks-cluster-config-handler.go

(cherry picked from commit a26114999119f364be1c3da8925d0f19bf2c68c2)
Occasionally when a conflict occurs during the reconciliation process, the `config` object that is returned is non-nil but empty, causing logs to be missing fields.
Issue #665 
**Checklist**:

[v2.9] fix: Retry operation on conflict

---

controller/aks-cluster-config-handler.go

Updating Availability Zone is not allowed for Azure AKS.
Issue: https://github.com/rancher/aks-operator/issues/669 (cherry picked from commit cb6780187745046ffe68850fb90a8ae468a23bb1)
Issue #
**Checklist**:

[v2.9] Add validation for modifications to availability zones

---

controller/aks-cluster-config-handler.go

Reverts rancher/aks-operator#670

Revert "[v2.9] fix: Retry operation on conflict"

---

.github/workflows/release.yaml
.github/workflows/scan.yaml
.trivyignore
package/Dockerfile

Bump base image version to 15.6. Also updated release and scan workflows to use the same version of Go, which is the one specified in go.mod.
**Checklist**:

[v2.7] Bump image version

---

.github/workflows/release.yaml
.github/workflows/scan.yaml
.trivyignore

We bump the version of the Go compiler used to build the operator itself in order to protect from any vulnerabilities that are present in older versions of the compiler. Note that we intentionally do not bump the version of the Go module as it's imported by Rancher 2.7.
The list of CVEs addressed:
- CVE-2023-45288
- CVE-2024-24790
- CVE-2024-34156
**Checklist**:

ci: Use Go 1.23

---

.github/workflows/scan.yaml

We frequently get CI failures when scanning with trivy because there have been too many requests to download the vulnerability db from the rancher org (because many of its repos are using it).
This PR updates the Scan workflow to include additional repositories to be used if trivy fails to retrieve the vulnerability db from the primary source.  
Issue #708 
Source for fix: https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-10884984
**Checklist**:

ci: Fix trivy action timeout

---

.github/workflows/scan.yaml

(cherry picked from commit f00d6665e1a1bf729ba48110de821a27448c07f4)
We frequently get CI failures when scanning with trivy because there have been too many requests to download the vulnerability db from the rancher org (because many of its repos are using it).
This PR updates the Scan workflow to include additional repositories to be used if trivy fails to retrieve the vulnerability db from the primary source.
Issue #708 
Source for fix: https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-10884984
**Checklist**:

[v2.9] ci: Fix trivy action timeout

---

.github/workflows/release.yaml
.github/workflows/scan.yaml
Makefile
package/Dockerfile

This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also updates the release workflow to additionally push images to Prime Registry.
Finally it uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #748 
**Checklist**:

ci: Make release SLSA compliant

---

.github/workflows/release.yaml
.github/workflows/scan.yaml
Makefile
package/Dockerfile

This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #748
**Checklist**:

[2.9] ci: Make release SLSA compliant

---

Makefile

To resolve errors such as [this](https://github.com/rancher/aks-operator/actions/runs/12369946845/job/34531199905) and [this](https://github.com/rancher/aks-operator/actions/runs/12375978658/job/34542030716#step:4:1448) the REPO variable must not include the image name.
Issue #748 
**Checklist**:

[2.9] ci: Change variable to align with what `publish-image` workflow expects

---

.github/workflows/release.yaml

Disabled pushing to Prime registry until SCC sorts out push errors
```
ERROR: failed to solve: failed to push ***/***/aks-operator:v1.9.6-rc.3: failed to authorize: failed to fetch oauth token: Post "https://scc.suse.com/api/registry/authorize": net/http: TLS handshake timeout
```
Issue #748 
**Checklist**:

[2.9] ci: Disable pushing to Prime registry

---

.github/workflows/release.yaml

Split the image publishing step from the GH release creation step. The reason is that since we now use a matrix to publish images, we don't want the GH release creation step to run multiple times, just once.
Issue #748 
**Checklist**:

[2.9] ci: Split image publishing from creating GH release

---

.github/workflows/release.yaml

A previous change in the Makefile resulted in the image name being generated to be rancher/aks-operator/aks-operator instead of rancher/aks-operator. This PR addresses this.
**Checklist**:

[v2.9] ci: Fix repo name in values.yaml

---

.github/workflows/release.yaml

A previous change in the Makefile resulted in the image name being generated to be `rancher/aks-operator/aks-operator` instead of `rancher/aks-operator`. This PR addresses this.
**Checklist**:

[v2.10] ci: Fix repo name in values.yaml

---

main.go
pkg/version/version.go

As part of https://github.com/rancher/aks-operator/pull/803 we already pass version and git sha information during `go build`.  This PR outputs this information when the operator starts to assist with troubleshooting.
Issue #726 
**Checklist**:

fix: Print build commit SHA during startup

---

main.go
pkg/version/version.go

(cherry picked from commit 472dc2a7dfc30ebc452691937def1e2eae793f02)
As part of https://github.com/rancher/aks-operator/pull/804 we already pass version and git sha information during go build. This PR outputs this information when the operator starts to assist with troubleshooting.
Issue #726 
**Checklist**:

[2.10] fix: Print build commit SHA during startup

---

main.go
pkg/version/version.go

(cherry picked from commit 472dc2a7dfc30ebc452691937def1e2eae793f02)
As part of https://github.com/rancher/aks-operator/pull/805 we already pass version and git sha information during go build. This PR outputs this information when the operator starts to assist with troubleshooting.
Issue #726 
**Checklist**:

[2.9] fix: Print build commit SHA during startup

---

.github/workflows/release.yaml

Push release artifacts to Prime registry.
**Checklist**:

[2.10] ci: Re-enable pushing to Prime registry

---

.github/workflows/release.yaml

Push release artifacts to Prime registry.
**Checklist**:

[2.9] ci: Re-enable pushing to Prime registry

---

.github/workflows/release.yaml
Makefile
main.go
package/Dockerfile
pkg/version/version.go

This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #748 
**Checklist**:

[2.8] ci: Make release SLSA compliant

---

.github/workflows/e2e-branch.yaml
.github/workflows/e2e-workflow.yaml
Makefile

Push test images to `ghcr.io` instead of `ttl.sh`.
**Checklist**:

ci: Push test images to ghcr.io instead of ttl.sh

---

controller/aks-cluster-config-handler.go
controller/aks-cluster-config-handler_test.go

in case a conflict error occurs the controller's recordError Function will just print it and return the error as it is.
conflict errors occur since rancher also modifies aksconfig object. As conflict error returns empty object, errors like `Error recording akscc [] failure message: resource name may not be empty` occurs when we try to add a failure message to aksconfig status and update it.
The operation which results in conflict gets applied automatically in the next reconciliation call of the controller hence it is safe to just log it.
Issue # 
https://github.com/rancher/aks-operator/issues/665
**Checklist**:

[main] added a debug log for conflict error and unit test for it

---

controller/aks-cluster-config-handler.go

While updating multiple fields, changes were being applied one by one. During this process, the system periodically polls the cluster for status updates. However, the cluster status was prematurely transitioning to active instead of updating. This led to:
- Some updates being reverted.
- Certain changes getting skipped intermittently.
To address this, we now ensure that while making updates, the cluster status is enqueued as updating. This keeps the cluster continuously checking for upstream changes and prevents unintended timeouts.
[Issue #667](https://github.com/rancher/aks-operator/issues/667)
**Checklist**:

[main] Prevent the cluster status from becoming active prematurely

---

controller/aks-cluster-config-handler.go

https://github.com/rancher/aks-operator/issues/877

[backport][v2.10] Prevent the cluster status from becoming active prematurely

---

.github/dependabot.yml

Enhance the Dependabot configuration to include the lasso package and adjust ignore rules for dependencies in the release-v2.8 branch.

[release-v2.8] update dependabot configuration to ignore lasso

---

.github/dependabot.yml

Enhance the Dependabot configuration to include the lasso dependency and adjust ignore rules for the release-v2.9 branch.

[release-v2.9]update dependabot configuration to ignore lasso

---

.github/dependabot.yml

Enhance the Dependabot configuration to include Go modules for the release-v2.10 branch and adjust ignored dependencies for better management of updates.

[release-v2.10] update dependabot configuration to ignore lasso

---

.github/dependabot.yml

Include the github.com/rancher/lasso dependency in the Dependabot updates for multiple release branches.

[main] update dependabot configuration to ignore lasso

---

controller/aks-cluster-config-handler.go

Previously, adding a NodePool with no availability zone` (AvailabilityZones == nil)` was failing due to an issue with `reflect.DeepEqual()`. The method was not handling nil and empty slices correctly, causing unexpected mismatches between `np.AvailabilityZones` and `upstreamNodePool.AvailabilityZones`.
We replaced `reflect.DeepEqual()` with a custom function, `availabilityZonesEqual()`, which properly handles:
- Nil vs. empty slice comparisons
- Cases where both values are nil
- Ensuring element-wise comparison for non-nil slices
- https://github.com/rancher/aks-operator/issues/850

[main] improve availability zone comparison logic

---

.github/workflows/delete-old-versions.yaml

Introduce a job that removes outdated package versions from the GitHub Container Registry, retaining a specified number of recent versions.
https://github.com/rancher/aks-operator/issues/818

[main] Update workflow to delete old package versions from GHCR registry

---

charts/aks-operator/Chart.yaml

- Bump rancher-version and kube-version
- https://github.com/rancher/rancher/issues/49163

[v2.10] Bump rancher-version and kube-version

---

.github/workflows/delete-old-versions.yaml

Introduce a new scheduled job to run the workflow every Thursday in addition to the existing Monday schedule.

[main] Add Thursday schedule to delete old images and charts workflow

---

.github/workflows/release.yaml
charts/aks-operator/Chart.yaml

- Add support for auto chart bump in release GHA
- New charts will be pushed to the branch with the name chart/[MAJOR-VERSION].[MINOR-VERSION]
- Bump `rancher-version` and `kube-version`
- https://github.com/rancher/rancher/issues/49163

[v2.11] Add support for auto chart bump in release GHA

---

.github/workflows/release.yaml
charts/aks-operator/Chart.yaml

- Add support for auto chart bump in release GHA
- New charts will be pushed to the branch with the name chart/[MAJOR-VERSION].[MINOR-VERSION]
- Bump `rancher-version` and `kube-version`
- https://github.com/rancher/rancher/issues/49163

[v2.9] Add support for auto chart bump in release GHA
