rancher/aks-operator

controller/aks-cluster-config-handler.go, crds/aksclusterconfig.yaml, examples/create-windows-example.yaml, internal/aks/create.go, pkg/apis/aks.cattle.io/v1/types.go, pkg/apis/aks.cattle.io/v1/zz_generated_deepcopy.go
Adds support for `WindowsProfile` which is required for Windows node pools.
https://github.com/rancher/rancher/issues/32586
=> Add WindowsProfile field

controller/aks-cluster-config-handler.go, examples/import-example.yaml
Also fix examples for imported clusters.
=> Don't delete node pools for imported clusters

controller/aks-cluster-config-handler.go
During upgrading node pools there has to be additional phase check
=> Add upgrading state for node pools

controller/aks-cluster-config-handler.go
Issue https://github.com/rancher/rancher/issues/32999
=> Set DNS prefix for upstreamSpec

controller/aks-cluster-config-handler.go
Issue: https://github.com/rancher/rancher/issues/33049
=> Fix updating Auto Scaling

controller/aks-cluster-config-handler.go, pkg/aks/create.go
=> Fix Azure monitoring options

controller/aks-cluster-config-handler.go
If a user updates the AKS cluster in AKS console, a transitory state may
be synced. Once Rancher sees this middle state, it will try to reconcile
back to this undesired state after the update completes in AKS.
With this change, aks-operator recognizes when an update was non
initiated by Rancher. It will then ignore the update until the AKS
cluster is in a "Succeeded" state.
Co-authored-by: Ricardo Weir <ricardo@rancher.com>
Issue:
https://github.com/rancher/rancher/issues/33446
=> Wait for non-Rancher initiated updates to complete

controller/aks-cluster-config-handler.go
This change does two things:
1. Perform control plane upgrades first. This will make it possible
to upgrade both the control plane and node pool kubernetes versions
at the same time, because the controller will safely make the
control plane changes first.
2. Only make changes to the current upstream node pools in the
cluster's AgentPoolProfiles list during the control plane update.
Without this, if a node pool is added with a version different from
the current upstream control plane version, AKS rejects it with this
error:
OrchestratorVersion must be all specified or all unspecified. If
all specified, they must be stay unchanged or the same with
control plane.
Filter out the new ones, and then add them in the node pool update
section after the control plane update is finished. …
=> Fix order of control plane and node pool upgrade

charts/aks-operator-crd/Chart.yaml, charts/aks-operator/Chart.yaml, charts/aks-operator/templates/_helpers.tpl, charts/aks-operator/templates/deployment.yaml, charts/aks-operator/values.yaml
This PR adds new annotations for app and marketplace UI changes. It also adding the correct tolerations and selectors for running in a mixed workload cluster.
* https://github.com/rancher/rancher/issues/36401
Verified that it will deploy in a mixed workload cluster successfully after the changes.
Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>
=> Changes required to support mixed workload clusters.

charts/aks-operator/templates/deployment.yaml, charts/aks-operator/values.yaml
Current nodeSelectors and tolerations are broken if you try supplying anything except default.
Larger PR: https://github.com/rancher/charts/pull/1813
=> Fix nodeSelectors and tolerations

controller/aks-cluster-config-handler.go
Issue: https://github.com/rancher/rancher/issues/37608 
When a private AKS cluster is provisioned, `aks-operator` tries to eternally remove auto-generated tags from the upstream spec which prevents the cluster from becoming active.
The solution here is for rancher to move on if a tags update returns an unexpected response from Azure. In other words, if Azure doesn't return the requested state for the tags string map and also an HTTP OK, then the `aks-operator` will move on instead of enqueuing a tags update. Any tags automatically added back to the cluster resource by Azure will be added back to rancher on the next sync.
* Provision an AKS cluster using the Rancher UI (it can be non-private. The bug is seen regardless)
* Verify that the default Azure tags were synced to the Rancher config …
=> Add default Azure tags to config spec to fix sync loop

controller/aks-cluster-config-handler.go, pkg/aks/create.go
Issue: https://github.com/rancher/rancher/issues/37681  
When creating or updating an AKS cluster, the aks operator does not check to see if a `managedCluster` object already exists and creates a new `managedCluster` object with only fields it knows about. This results in some fields associated with an existing cluster in Azure being overwritten on the `CreateOrUpdate` API call in `create.go`. When the aks operator does a sync and builds a config based on the state of the upstream AKS cluster, there is also a bug where authorized IP ranges configured in Azure will get overwritten with a nil value because rancher doesn't dereference the *[]string properly. Thus, the authorized IP range won't show up in the UI.
I've refactored `create.go` in the aks operator to separate out the create and …
=> Fix field overwrite for cluster creation/update actions in AKS

pkg/aks/create.go
Issue: https://github.com/rancher/rancher/issues/37681
=> Fix bug in aks http application routing update

controller/aks-cluster-config-handler.go
Issue: https://github.com/rancher/rancher/issues/39259
Duplicate error message
=> Fix error msg

Dockerfile.dapper, package/Dockerfile
- Align to standardized `bci-base`
- Bump to 15.4 as 15.3 is EOL
=> Use BCI image and bump to 15.4

charts/aks-operator-crd/templates/crds.yaml, controller/aks-cluster-config-handler.go, pkg/aks/create.go, pkg/aks/create_test.go, pkg/aks/update_test.go, pkg/apis/aks.cattle.io/v1/types.go, pkg/apis/aks.cattle.io/v1/zz_generated_deepcopy.go
Fixes https://github.com/rancher/rancher/issues/40214
=> Add Nodes Labels, Taints and MaxSurge to AgentPool

.github/workflows/apidiff.yaml, Makefile
This workflow will notify if we break compatibility with the aks operator API.
=> Add apidiff workflow

Dockerfile.dapper, package/Dockerfile
Backport of https://github.com/rancher/aks-operator/pull/81
=> [release/v1.0] Use BCI image and bump to 15.4

Makefile, pkg/aks/create.go, pkg/aks/create_test.go, pkg/aks/update.go, pkg/aks/update_test.go
Refactor create/update code to make it more readable. I also added new unit tests.
=> Refactor create/update code to make it more readable

go.mod, go.sum
Bump wrangler together with Rancher version
https://github.com/rancher/rancher/pull/40649
=> Update wrangler to v1.1.0

Makefile, README.md, test/e2e/deploy_operator_test.go
=> Update readme with new information

pkg/aks/create.go
Issue: https://github.com/rancher/rancher/issues/41927
=> Check if NodeTaints is nil

.github/scripts/update-rancher-charts.sh
See https://github.com/rancher/eks-operator/pull/177 for context
=> Fix chart update workflow

charts/aks-operator-crd/templates/crds.yaml, controller/aks-cluster-config-handler.go, controller/aks-cluster-config-handler_test.go, pkg/aks/create.go, pkg/aks/create_test.go, pkg/apis/aks.cattle.io/v1/types.go, pkg/apis/aks.cattle.io/v1/zz_generated_deepcopy.go
Issue: https://github.com/rancher/aks-operator/issues/131
=> Add PrivateDNSZone for private clusters

controller/aks-cluster-config-handler.go
Issues: https://github.com/rancher/aks-operator/issues/249
=> Fix update mode for node pool groups

controller/aks-cluster-config-handler.go, controller/aks-cluster-config-handler_test.go
Issue: rancher/gke-operator#122
cc: @rancher/highlander
=> Check for duplicate names for NodePools

controller/aks-cluster-config-handler.go, controller/aks-cluster-config-handler_test.go
Issue: https://github.com/rancher/gke-operator/issues/122
cc: @rancher/highlander 
(cherry picked from commit cd7b98b89a3a35b17309ca29f14e62dffd1e7548)
=> [2.8] Check for duplicate names for NodePools

controller/aks-cluster-config-handler.go
Issue: https://github.com/rancher/aks-operator/issues/294
=> Fix for updating imported clusters

.github/workflows/build.yaml, .github/workflows/e2e-latest-rancher.yaml, .github/workflows/lint.yaml, .github/workflows/scan.yaml, .github/workflows/unit.yaml
We have to update default branch name for CI workflows
Issue #
**Checklist**:
=> Fix main branch name in workflows

README.md
Adds a label to the readme with the status of the e2e tests
Issue #
**Checklist**:
=>  docs: update readme with e2e badge

.github/workflows/apidiff.yaml, .github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/lint.yaml, .github/workflows/unit.yaml, .github/workflows/verify.yaml, Dockerfile.dapper, go.mod, test/e2e/Dockerfile.e2e, test/e2e/config/config.go
=> Bump go version to 1.21

.github/workflows/apidiff.yaml, .github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/lint.yaml, .github/workflows/unit.yaml, .github/workflows/verify.yaml, Dockerfile.dapper, go.mod, test/e2e/Dockerfile.e2e, test/e2e/config/config.go
=> [v2.8] Bump go version to 1.21

.github/dependabot.yml
=> Ignore github.com/rancher/rancher/pkg/apis by dependabot

Dockerfile.dapper, go.mod
=> [v2.9] Revert github.com/rancher/rancher/pkg/apis version

.github/workflows/lint.yaml, test/e2e/config/config.go
(cherry picked from commit 7ce428587c9b2782f447215209a02c46074bd3fb) (cherry picked from commit 5bdaf852a489da7aab5e50d71b436ab599acf994) (cherry picked from commit 7041482c4550d52212fc4b28b3596f9090a599b6)
Issue #
**Checklist**:
=> [v2.7] Satisfy golangci-lint and fix tests

.github/workflows/lint.yaml, .github/workflows/scan.yaml, .github/workflows/unit.yaml, .github/workflows/verify.yaml
Issue https://github.com/rancher/aks-operator/issues/432
**Checklist**:
=> Run CI jobs on release branches

.github/workflows/release.yaml
=> Final fixes to release.yaml

go.mod, go.sum
Issue # https://github.com/rancher/aks-operator/security/dependabot/37
**Checklist**:
=> [v2.8] fix: Bump `github.com/rancher/norman` version to address CVE-2023-32193

charts/aks-operator/templates/deployment.yaml
Issue https://github.com/rancher/aks-operator/issues/482
**Checklist**:
=> Update systemDefaultRegistry in helm chart

charts/aks-operator/templates/deployment.yaml
Issue: https://github.com/rancher/aks-operator/issues/482 (cherry picked from commit 2a5bb41ee53164467dd7ecdbaf73c6faf9d435e9)
Issue #
**Checklist**:
=> [v2.9] Update systemDefaultRegistry in helm chart

charts/aks-operator/templates/deployment.yaml
Issue: https://github.com/rancher/aks-operator/issues/482 (cherry picked from commit 2a5bb41ee53164467dd7ecdbaf73c6faf9d435e9)
Issue #
**Checklist**:
=> [v2.8] Update systemDefaultRegistry in helm chart

go.mod, go.sum
=> Bump k8s.io/kubernetes to v1.29.3

go.mod, go.sum
=> [v2.7] Bump k8s.io/kubernetes to v1.27.13

go.mod, go.sum
=> [v2.9] Bump k8s.io/kubernetes to v1.29.3

Dockerfile.dapper
=> Bump go version to v1.21.10

Dockerfile.dapper, Makefile
=> Disable C calls from GO in operator

controller/aks-cluster-config-handler.go
=> Update log message when tags are not updated

controller/aks-cluster-config-handler.go
(cherry picked from commit b9c1ebb6ad6be1932468fa59ca3d87f96d65544a)
Issue #
**Checklist**:
=> [v2.9] Update log message when tags are not updated

controller/aks-cluster-config-handler.go
(cherry picked from commit b9c1ebb6ad6be1932468fa59ca3d87f96d65544a)
Issue #
**Checklist**:
=> [v2.8] Update log message when tags are not updated

go.mod
=> [v2.9] Remove toolchain from go.mod

pkg/aks/update.go
Issue: https://github.com/rancher/aks-operator/issues/531
Issue #
**Checklist**:
=> [v2.8] Remove custom kubelet and linux os configs before updating

scripts/setup-kind-cluster.sh
=> [v2.9] Drop support for Kubernetes v1.25

charts/aks-operator/templates/deployment.yaml
1. Restrict container from acquiring additional privileges (`securityContext.allowPrivilegeEscalation`)
2. Mount container's root filesystem as read only (`securityContext.readOnlyRootFilesystem`)
3. Ensure that container won't be started as privileged container (`securityContext.privileged`)
Issue: https://github.com/rancher/aks-operator/issues/591 (cherry picked from commit 7bc096f030238b2384c4ed7e5f1ae66ebf23be17)
Issue #
**Checklist**:
=> [v2.9] Improve securityContext for operator Deployment

go.mod, go.sum
=> [v2.8] Bump wrangler to v2.1.4

controller/aks-cluster-config-handler.go, pkg/aks/client.go, pkg/aks/create.go, pkg/aks/update.go
kind/enhancement
1. Use [cluster-name (id: cluster-id)] instead of either [cluster-name] or [cluster-id]
2. Log more information
Issue #
**Checklist**:
=> Enhance logs

controller/aks-cluster-config-handler.go, pkg/aks/client.go, pkg/aks/create.go, pkg/aks/update.go
- Add log format [cluster-name (id:cluster-id)]
- Increase log verbosity
- Add more debug messages
Signed-off-by: Parthvi <parthvi.vala@suse.com>
(cherry picked from commit bf1310f116a0001d59f74c240b30a982fdca8273)
Issue #
**Checklist**:
=> [v2.9] Enhance logs

.github/dependabot.yml
=> Drop v2.7 branch for dependabot

pkg/aks/create.go, pkg/aks/create_test.go
Issue: https://github.com/rancher/aks-operator/issues/640
Issue #
**Checklist**:
=> Allow to create empty tags

controller/aks-cluster-config-handler.go
Issue: https://github.com/rancher/aks-operator/issues/619
Issue #
**Checklist**:
=> Prevent from removing last node pool with mode System

controller/aks-cluster-config-handler.go
(cherry picked from commit https://github.com/rancher/aks-operator/pull/684/commits/3721b2c9f57578e5732cc7a12d9f81de93e0ebb8)
Reverts https://github.com/rancher/aks-operator/pull/668
=> Revert "[main] fix: Retry operation on conflict"

controller/aks-cluster-config-handler.go, pkg/aks/create.go
=> Remove deprecated azure-sdk-go modules

controller/aks-cluster-config-handler.go
=> Return error when updating az

.github/workflows/nightly-publish.yaml
Updates the nightly workflow to reflect latest change and remove an obsolete parameter from the referenced workflow.
https://github.com/rancher-sandbox/highlander-reusable-workflows/blob/6d9ba8b22d8a2b7cd81ce4ec07210b6025384872/.github/workflows/operator-with-latest-rancher-build.yaml
**Checklist**:
=> ci: Remove obsolete workflow parameter

.github/dependabot.yml, .github/workflows/e2e-workflow.yaml
Updated CI workflows to work with new 2.10 branch.
**Checklist**:
=> ci: Update workflows for 2.10

go.mod, go.sum
=> [v2.9] Bump golang.org/x/crypto to v0.31.0

go.mod, go.sum
=> [v2.8] Bump golang.org/x/crypto to v0.31.0

.github/workflows/release.yaml, .github/workflows/scan.yaml, Makefile, package/Dockerfile
(cherry picked from commit 355339c842414fd7ce7669bd842ae052aa83646d)
Issue #748 
**Checklist**:
=> [2.10] ci: Make release SLSA compliant

.github/workflows/release.yaml
Use correct Docker Hub credentials.
Issue #748 
**Checklist**:
=> ci: Use correct Docker Hub credentials

pkg/aks/create.go, pkg/aks/create_test.go
Issue: https://github.com/rancher/aks-operator/issues/640 (cherry picked from commit 61675fca856f493914694dc9b3c4e2330121fd5c)
Issue #
**Checklist**:
=> [v2.9] Allow to create empty tags

.github/workflows/release.yaml
Updated release workflow, to work around `goreleaser` dirty state error. For more context see https://github.com/rancherlabs/slsactl/pull/18. This is a temporary fix that we can remove once `rancher/ecm-distro-tools/actions/publish-image@main` gets updated.
Issue #748 
**Checklist**:
=> [2.9] ci: Cleanup checksum files from previous step

.github/workflows/release.yaml
Change release workflow to use EIO runner to check whether push errors are reduced. 
Issue #748 
**Checklist**:
=> [2.9] ci: Use EIO runner

controller/aks-cluster-config-handler.go, pkg/aks/create.go
(cherry picked from commit 8338522fc6e2845b943fbb816d5d9b6208fb531b)
Issue #
**Checklist**:
=> [v2.9] Remove deprecated azure-sdk-go modules

Makefile
Backport of https://github.com/rancher/aks-operator/pull/803
Issue #802 
**Checklist**:
=> [v2.8] VEX related improvements in the build process

.github/workflows/build.yaml, .github/workflows/release.yaml
Updating release workflow to wait for images to get published before creating a GH release.
Issue #
**Checklist**:
=> ci: Fix release workflow

.github/workflows/nightly-publish.yaml
This PR adds a new workflow job that pushes nightly images to ghcr.io. 
Issue #766 
**Checklist**:
=> ci: Push nightly images to ghcr.io

controller/aks-cluster-config-handler_test.go
fix a unit test case added in the PR: https://github.com/rancher/aks-operator/pull/849
added an after each to get rid of duplicate error in before each hook
Issue #
**Checklist**:
=> fix recorderror unit test

controller/aks-cluster-config-handler.go, controller/aks-cluster-config-handler_test.go
- https://github.com/rancher/aks-operator/issues/871
=> [backport][v2.10] added a debug log for conflict error and unit test for it

controller/aks-cluster-config-handler.go
backport : https://github.com/rancher/aks-operator/issues/876
=> [backport][v2.11] Prevent the cluster status from becoming active prematurely

controller/aks-cluster-config-handler.go
https://github.com/rancher/aks-operator/issues/930
=> [v2.10] improve availability zone comparison logic

controller/aks-cluster-config-handler.go
https://github.com/rancher/aks-operator/issues/931
=> [v2.11] improve availability zone comparison logic

.github/workflows/release.yaml
=> [release-v2.10] added go get dispatch workflow

.github/workflows/release.yaml
=> [release-v2.11] added go get dispatch workflow

.github/workflows/release.yaml
=> [main] added go get dispatch workflow

.github/workflows/release.yaml
- Add support for auto chart bump in release GHA
- New charts will be pushed to the branch with the name chart/[MAJOR-VERSION].[MINOR-VERSION]
- https://github.com/rancher/rancher/issues/49163
=> [v2.10] Add support for auto chart bump in release GHA

.github/workflows/release.yaml, charts/aks-operator/Chart.yaml
bumped the chart version to support v1.12
Issue [#48796](https://github.com/rancher/rancher/issues/48796)
**Checklist**:
=> bumped the chart version to support v1.12

go.mod, go.sum
upgraded the lasso and wrangler
Issue #
**Checklist**:
=> upgraded the lasso and wrangler

.github/workflows/e2e-workflow.yaml
added 2.12 in the e2e workflow 
Issue #
**Checklist**:
=> added 2.12 in the e2e workflow 

.github/dependabot.yml
updated dependabot workflow to add 2.12
Issue #
**Checklist**:
=> updated dependabot workflow to add 2.12

.github/workflows/release.yaml
removed dispatch dependency workflow
Issue #
**Checklist**:
=> [v2.11]removed dispatch dependency workflow
